### ISSUE TITLE
Strip units and return numbers where possible

### ISSUE THREAD

**Issue by yetkinergun** [richardlevy/solis-cloud-scraper#2]
First of all, thanks for the great work on the scraper 👍

As per the [limitations section](https://github.com/richardlevy/solis-cloud-scraper#restrictionslimitations) in the readme, the app is returning strings with values and units. What do you think about stripping the units and returning numbers where possible? I'll be piping this to openhab, influxdb and eventually grafana, and values like `"14.3kWh"` are not easy to store / visualise. 

Happy to make a PR if you'd like!

**Comment by richardlevy** [comment]
Hi.  V2 API endpoint added with typed data.

Let me know how it works for you.

**Comment by yetkinergun** [comment]
Thank you!
