### ISSUE TITLE
Website updated - new selectors

### ISSUE THREAD

**Issue by yetkinergun** [richardlevy/solis-cloud-scraper#4]
Hey Richard,

On 12th of April Solis made a small update to their animation and changed selectors for grid data.

House load: `.animation > .wrap > .grid-side > .content > span`
Today consumption: `.animation > .wrap > .grid-side > .use-power > span:nth-child(2)`

Hope this helps 👍

**Comment by richardlevy** [comment]
All updated - thanks!

**Comment by yetkinergun** [comment]
They've updated again! I've set up alerting on my side to capture these immediately when the website changes.

House load: `.animation > .wrap > .yongdian > .content > span`
Today consumption: `.animation > .bottomtext-info > div > .yongdian-info > div > span:nth-child(2)`

**Comment by richardlevy** [comment]
Was on todays todo list. Updated - thanks for selectors!Sent from my iPhoneOn 21 Apr 2023, at 12:13, Yetkin Ergun ***@***.***> wrote:﻿
They've updated again! I've set up alerting on my side to capture these immediately when the website changes.
House load: .animation > .wrap > .yongdian > .content > span
Today consumption: .animation > .bottomtext-info > div > .yongdian-info > div > span:nth-child(2)
